# Usage: KITCHEN_YAML=.kitchen.docker.yml bundle exec kitchen list
---
driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false

platforms:
- name: centos-5
  driver:
    image: centos:5
    platform: rhel
    run_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install which initscripts net-tools wget
  attributes:

- name: centos-6
  driver:
    image: centos:6
    intermediate_instructions:
      - RUN yum -y install tar which initscripts
  attributes:

- name: centos-7
  driver:
    image: centos:7
    intermediate_instructions:
      - RUN yum clean all
      - RUN yum -y install net-tools lsof which
    pid_one_command: /usr/lib/systemd/systemd
  attributes:

- name: debian-7
  driver:
    image: debian:7
    run_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y
  attributes:

- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y
  attributes:

- name: fedora-latest
  driver:
    image: fedora:latest
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y install yum tar which systemd-sysv initscripts

- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y
  attributes:

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y
  attributes:

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y
  attributes:

suites:
- name: default
  run_list:
    - phantomjs2
  attributes:
